### ISSUE TITLE
Package python-pip is not available, but is referred to by another package

### ISSUE THREAD

**Issue by ChicagoGregg** [MohamedElashri/Zotero-Docker#29]
I'm excited to find a dataserver docker image on GitHub here that has been touched in the past ~3 months! Thanks for putting it out there.

I'm trying to build the docker image, but am getting the below under both macOS Catalia 10.15.7 and CentOS 7. I'm not too skilled at the inner workings of docker (yet, but getting there!) so I wouldn't know what is causing this. I haven't been able to find other links showing how to fix this (specifically for Zotero dataserver). If someone could help on this it'd be greatly appreciated! Thanks!

==========
Starting to download Net_URL2-2.2.1.tgz (20,010 bytes)
...done: 20,010 bytes
install ok: channel://pear.php.net/Net_URL2-2.2.1
install ok: channel://pear.php.net/HTTP_Request2-2.4.2
Removing intermediate container 50c0ac6f1901
 ---> 63e1ef6562d4
Step 28/54 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python python-pip rsync git wget rinetd
 ---> Running in 9c977564ca67
Reading package lists...
Building dependency tree...
Reading state information...
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate
ERROR: Service 'app-zotero' failed to build: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get -y install python python-pip rsync git wget rinetd' returned a non-zero code: 100
==========

**Comment by MohamedElashri** [comment]
`python-pip` is in the universe repositories, therefore use the steps below for your case: 

```sudo apt-get install software-properties-common
sudo apt-add-repository universe
sudo apt-get update
sudo apt-get install python-pip```

Ultimately this image is working fine with Ubuntu as this is my OS that I'm using and tested.

**Comment by ChicagoGregg** [comment]
Thanks @MohamedElashri ! I actually should have picked up on that. I thought I was on my CentOS server (where I have all the tools installed), but was on my Mac. I also just switched the Dockerfile python-pip to use python3-pip (since yum didn't find python-pip anyways and that's what it suggested).

FYI, there are some other fixes in the instructions that could be refined. I went over to zotero-prime and was able to fill in some blanks for some (e.g. init mysql database).

After further review, I'm not sure if this will be a good fit for me since the Zotero dataserver seems it will ONLY interface to Amazon AWS (S3) and I have a need to keep the data on the local network (local filesystem preferred). I wrote the zotero-dev to see if someone could help validate.

Thanks for the help!

**Comment by MohamedElashri** [comment]
Hi 

Sorry for very late reply, I'm sorry that this project is incomplete until now. It is promising but time-consuming and I'm busy this summer with my PhD qual exam preparations . 

> FYI, there are some other fixes in the instructions that could be refined. I went over to zotero-prime and was able to fill in some blanks for some (e.g. init mysql database).
You are right, I should have done this, I'm surprised that you and couple got interested in this personal project that I don't update it often. My main goal was to combine web library which still something I didn't achieve without problems so hopefully I manage to make it work after my exam. 

> After further review, I'm not sure if this will be a good fit for me since the Zotero dataserver seems it will ONLY interface to Amazon AWS (S3) and I have a need to keep the data on the local network (local filesystem preferred). I wrote the zotero-dev to see if someone could help validate.

Yes but this project don't use AWS S3 but self hosted S3 compatible protocol  **minio**
For example the first script to install should be `init.sh` which setup minio on your local system (so it is truly self-hosted)

Good luck
